env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:jest/recommended
  - airbnb
  - prettier
  - plugin:import
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
settings:
  import/resolver:
    jsconfig:
      config: "jsconfig.json"
rules:
  react/function-component-definition:
    - 2
    - namedComponents: "arrow-function"
    - unnamedComponents: "arrow-function"
