version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    volumes:
      - ./app/psychological-test:/usr/src/app
    tty: true
    command: sh -c "yarn run start"
    ports:
      - "3000:3000"